---
- hosts: localhost
  become: true
  connection: local
  vars:
    sensu_checks:
      - name: 'cpu'
        command: 'check-cpu.rb'
        interval: 60
        subscribers:
          - 'test'
          - 'ALL'
        state: 'present'
      - name: 'disk-usage'
        command: 'check-disk-usage.rb -w 80 -c 90'
        interval: 60
        subscribers:
          - 'test'
          - 'ALL'
        state: 'present'
      - name: 'memory'
        command: 'check-memory.rb -w 2500 -c 3000'
        interval: 60
        subscribers:
          - 'test'
          - 'ALL'
        state: 'present'
      - name: 'memory-percent'
        command: 'check-memory-percent.rb -w 70 -c 80'
        interval: 60
        subscribers:
          - 'test'
          - 'ALL'
        state: 'present'
      - name: 'test'
        command: 'echo -n OK'
        interval: 60
        subscribers:
          - 'test'
          - 'ALL'
    state: 'present'
  roles:
  tasks:
    - name: Checking For RabbitMQ Connection
      wait_for:
        port: 5672
        host: rabbitmq

    - name: Checking For Redis Connection
      wait_for:
        port: 6379
        host: redis

    - name: Configuring Sensu
      template:
        src: "/config.json.j2"
        dest: "/etc/sensu/config.json"

    - name: Configuring Uchiwa
      template:
        src: "/uchiwa.json.j2"
        dest: "/etc/sensu/uchiwa.json"

    - name: Managing Sensu Checks
      sensu_check:
        name: "{{ item.name }}"
        command: "{{ item.command }}"
        interval: "{{ item.interval }}"
        subscribers: "{{ item.subscribers|join (',')}}"
        state: "{{ item.state }}"
      with_items: '{{ sensu_checks }}'
